/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
//        ticket.booking.App classUnderTest = new ticket.booking.App();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
